apiVersion: v2
name: control-plane
description: Synadia Control Plane
home: https://www.synadia.com/
type: application
version: 1.2.1
appVersion: 1.2.1
maintainers:
- name: Synadia
  url: https://github.com/synadia-io
  email: info@synadia.com
